changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Mod
      labels:
        - mod
        - gameplay
    - title: Resource Pack
      labels:
        - resource-pack
        - textures
    - title: Shader Pack
      labels:
        - shader-pack
        - visuals
    - title: Documentacao
      labels:
        - documentation
    - title: Outros Ajustes
      labels:
        - "*"
